### ISSUE TITLE
Parameter 

### ISSUE THREAD

**Issue by vu-dang** [felix-d-git/DesktopAppLink#1]
How to send parameters to the app?  I have a command line app that expects parameters.  How do I format the URL to send parameters to the command line program?

**Comment by felix-exon** [comment]
@vu-dang sorry for the late response. I've made some edits. See if this solved your problem.

<a href="mycustomprotocol:origin=web">Click me!</a>

Note that after the ":" the can only be 1 string. If you need to pass multiple parameters you need to join them into 1 string. 

For example 
```html
<a href="mycustomprotocol:args=arg1,arg2,arg3,arg4,arg5">Click me!</a>
```
Your app will recieve this:
```
string arg = mycustomprotocol:args=arg1,arg2,arg3,arg4,arg5

string argString = arg.SubString(arg.FirstIndexOf('='), arg.Length - arg.FirstIndexOf('='));
string[] realArgs =argString.Split(',');
```
