### ISSUE TITLE
opening quick assist with web link. 

### ISSUE THREAD

**Issue by ijiboy** [felix-d-git/DesktopAppLink#4]
Hi, 
just starting my career in coding and want to know if opening quick assist which is a default desktop application in Windows could be opened from a web link. 

<p><a href="ms-photos:viewer?" target="_blank" role="button" class="ocpExternalLink supLinkButton x-hidden-focus" ms.cmpgrp="content" ms.pgarea="Body">Change product key in Settings</a>
</html>
this allows me to open the setting, photos and other default applications. 

I would like to do the same with quick assist application to open up via a link attached to my company website page. 

kindest regards, rex

**Comment by felix-exon** [comment]
This is easily possible.
The QuickAssist application can be found here: `"C:\WINDOWS\system32\quickassist.exe"`.
All you need to do is register a custom protocol in your application. Theren register a handler for a certain link and open QuickAssist via `Process.Start("C:\WINDOWS\system32\quickassist.exe")`.
